name: .NET Core CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    # Restore
    - name: Restore dependencies
      run: dotnet restore MyDotNetAppAPI/MyDotNetAppAPI.csproj

    # Build
    - name: Build
      run: dotnet build MyDotNetAppAPI/MyDotNetAppAPI.csproj --no-restore --configuration Release

    # Test
    - name: Test
      run: dotnet test MyDotNetAppAPI/MyDotNetApp.Tests/MyDotNetApp.Tests.csproj --no-build --configuration Release --verbosity normal

    # Publish
    - name: Publish
      run: dotnet publish MyDotNetAppAPI/MyDotNetAppAPI.csproj --configuration Release --output publish/

    # Upload artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MyDotNetAppAPI
        path: publish/
